(in-package :cl-booru)
(defparameter sb-fastcgi::*read-buffer-size* (* 1024 1024 4))

(defconstant +results-per-page+ 24)
(defconstant +max-post-results+ 240)
(defconstant +site-title+ "SampleBooru")
(defconstant +salt+ "salty")
(defconstant +session-salt+ "saltier")
(defparameter *db-name* "samplebooru")
(defparameter *db-user* "samplebooru")
(defparameter *db-password* "password")
(defparameter *db-host* "host.example")
(defparameter *site-root* (pathname "/opt/samplebooru/web/"))
(defparameter *site-images-root* (merge-pathnames "images/" *site-root*))
(defparameter *site-images-full* (merge-pathnames "full/" *site-images-root*))
(defparameter *site-images-thumb* (merge-pathnames "thumb/" *site-images-root*))
(defparameter *image-thumb-size* 192)
(defparameter *template* (lambda (page) (format nil "~A" page)))
